### ISSUE TITLE
Sourcing of AMBE3003 parts

### ISSUE THREAD

**Issue by m1geo** [phl0/AMBE3003USB#1]
Hi gents. Where did you obtain AMBE 3003 parts from in hobby quantities? Thanks, George, M1GEO.

**Comment by m1geo** [comment]
Ignore that, I found that they do a 6-piece order minimum for one time. Details on [dvsinc price list](https://www.dvsinc.com/products/price.shtml).

**Comment by phl0** [comment]
> Ignore that, I found that they do a 6-piece order minimum for one time. Details on [dvsinc price list](https://www.dvsinc.com/products/price.shtml).

Thats exactly what I did. Apparently you can only order that 6 pieces ones. Thats why I only did 3 PCBs :(

**Comment by m1geo** [comment]
Gets pricey quickly; I was hoping to make a few with AMBE3003, but a MoQ of $500 USD for 6 chips is no joke.

**Comment by dave31418** [comment]
When I ordered some of the AMBE3000's , DVSI failed to let me know subsequent orders would need to be for larger quantities.   Not knowing this I developed a board and I sold a few interfaces but since I only started with 10 they didn't go far.   Every month I get a few inquiries about the next build.    I'm considering ordering the minimum quantity just so I can do a build.    This becomes an easier decision if some of you guys want a few.   I would be happy to share at cost plus shipping.    I don't know but that may violate their terms of service if I distribute them.   I will look into this.    ( I am speaking AMBE3000 not the 3003 )

**Comment by m1geo** [comment]
I could be interested in that; **3x**AMBE3000 vs **1x**AMBE3003 is cheaper, and I don't care about size at all as these are for a VHF WebSDR (openwebrx). In fact, **3x**AMBE3000 is probably better, in some regards. If you're seriously considering this, drop me an [email](http://www.george-smart.co.uk/cgi-bin/socialmedia.cgi/email).
